name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Load secret files
        env:
          - GOOGLE_SERVICES_JSON_DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
          - SIGN_KEY_DATA: ${{ secrets.SIGN_KEY }}
          - KEY_STORE_PROP_DATA: ${{ secrets.KEY_STORE_PROP }}
        run: |
          echo $GOOGLE_SERVICES_JSON_DATA | base64 -di > app/google-services.json 
          echo $SIGN_KEY_DATA | base64 -di > MUEDSA.jks
          echo $KEY_STORE_PROP_DATA | base64 -di > keystore.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
      - name: Upload a Build Artifact
        if: success()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: build-artifact
          path: |
            ./**/*.apk